/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.hephy.Rave;

public class rave {
  public static boolean RaveEquals(RavePoint3D lhs, RavePoint3D rhs) {
    return raveJNI.RaveEquals__SWIG_0(RavePoint3D.getCPtr(lhs), lhs, RavePoint3D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveVector6D lhs, RaveVector6D rhs) {
    return raveJNI.RaveEquals__SWIG_1(RaveVector6D.getCPtr(lhs), lhs, RaveVector6D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance3D lhs, RaveCovariance3D rhs) {
    return raveJNI.RaveEquals__SWIG_2(RaveCovariance3D.getCPtr(lhs), lhs, RaveCovariance3D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance6D lhs, RaveCovariance6D rhs) {
    return raveJNI.RaveEquals__SWIG_3(RaveCovariance6D.getCPtr(lhs), lhs, RaveCovariance6D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RavePerigeeParameters3D lhs, RavePerigeeParameters3D rhs) {
    return raveJNI.RaveEquals__SWIG_4(RavePerigeeParameters3D.getCPtr(lhs), lhs, RavePerigeeParameters3D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RavePerigeeParameters5D lhs, RavePerigeeParameters5D rhs) {
    return raveJNI.RaveEquals__SWIG_5(RavePerigeeParameters5D.getCPtr(lhs), lhs, RavePerigeeParameters5D.getCPtr(rhs), rhs);
  }

  public static String RaveVersion() {
    return raveJNI.RaveVersion();
  }

  public static boolean RaveEquals(RaveVector4D lhs, RaveVector4D rhs) {
    return raveJNI.RaveEquals__SWIG_6(RaveVector4D.getCPtr(lhs), lhs, RaveVector4D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveVector7D lhs, RaveVector7D rhs) {
    return raveJNI.RaveEquals__SWIG_7(RaveVector7D.getCPtr(lhs), lhs, RaveVector7D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance4D lhs, RaveCovariance4D rhs) {
    return raveJNI.RaveEquals__SWIG_8(RaveCovariance4D.getCPtr(lhs), lhs, RaveCovariance4D.getCPtr(rhs), rhs);
  }

  public static boolean RaveEquals(RaveCovariance7D lhs, RaveCovariance7D rhs) {
    return raveJNI.RaveEquals__SWIG_9(RaveCovariance7D.getCPtr(lhs), lhs, RaveCovariance7D.getCPtr(rhs), rhs);
  }

  public static SWIGTYPE_p_std__ostream RavePrint(SWIGTYPE_p_std__ostream os, RaveCovariance7D arg1) {
    return new SWIGTYPE_p_std__ostream(raveJNI.RavePrint__SWIG_0(SWIGTYPE_p_std__ostream.getCPtr(os), RaveCovariance7D.getCPtr(arg1), arg1), false);
  }

  public static boolean RaveEquals(RavePerigeeParameters6D lhs, RavePerigeeParameters6D rhs) {
    return raveJNI.RaveEquals__SWIG_10(RavePerigeeParameters6D.getCPtr(lhs), lhs, RavePerigeeParameters6D.getCPtr(rhs), rhs);
  }

  public static SWIGTYPE_p_std__ostream RavePrint(SWIGTYPE_p_std__ostream os, RavePerigeeParameters6D arg1) {
    return new SWIGTYPE_p_std__ostream(raveJNI.RavePrint__SWIG_1(SWIGTYPE_p_std__ostream.getCPtr(os), RavePerigeeParameters6D.getCPtr(arg1), arg1), false);
  }

  public static SWIGTYPE_p_std__ostream RavePrint(SWIGTYPE_p_std__ostream os, RavePerigeeCovariance6D arg1) {
    return new SWIGTYPE_p_std__ostream(raveJNI.RavePrint__SWIG_2(SWIGTYPE_p_std__ostream.getCPtr(os), RavePerigeeCovariance6D.getCPtr(arg1), arg1), false);
  }

}
